"""init

Revision ID: 1dd21460b1a3
Revises: 
Create Date: 2023-04-24 21:42:05.579816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd21460b1a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('stop_date',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('stop_date',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
